### PR TITLE
handleUnknownCallbackQuery

### PR DESCRIPTION
**Pull request by BeyCoder**
issue #373

### CODE REVIEW

**Comment by fabio-ivona** [comment]
Thanks @BeyCoder !

Would you mind to add some tests for this feature?

**Comment by BeyCoder** [comment]
> Thanks @BeyCoder !
> 
> Would you mind to add some tests for this feature? 

Sure, today/tomorrow i will commit 🙃

**Comment by BeyCoder** [comment]
> Thanks @BeyCoder !
> 
> Would you mind to add some tests for this feature?

Ready

**Comment by fabio-ivona** [comment]
I can't see the test, sorry :( am I missing something?

**Comment by BeyCoder** [comment]
> I can't see the test, sorry :( am I missing something?

image

**Comment by BeyCoder** [comment]
> I can't see the test, sorry :( am I missing something?

Maybe I did some mistake, so I'm not good at writing tests :(

**Comment by fabio-ivona** [comment]
https://github.com/defstudio/telegraph/blob/main/tests/Unit/Handlers/WebhookHandlerTest.php#L158

You can use this one as a reference 😉

**Comment by BeyCoder** [comment]
Now, should be okey :D

**Comment by fabio-ivona** [comment]
Thanks! Will check it soon 👍

**Pull request closed without merging**
