### PR TITLE
Implement `deleteChatPhoto` method

### LINKED ISSUE #191: Implement `deleteChatPhoto` method
ref https://core.telegram.org/bots/api#deletechatphoto

### PR DESCRIPTION
**Pull request by adevade**
Implements method for deleting chat photo.

Closes #191

### CODE REVIEW

**Comment by fabio-ivona** [comment]
Hi! Thanks for your contribution!

Would you mind to add a deletePhoto method to TelegraphChat model as well?

**Comment by adevade** [comment]
Sure, done! 👍

**Comment by adevade** [comment]
Fixed the merge conflict

**Comment by fabio-ivona** [comment]
Thanks  @adevade :raised_hands:

**Pull request merged**
