### PR TITLE
implement `setChatMenuButton` method

### LINKED ISSUE #194: Implement `setChatMenuButton`
https://core.telegram.org/bots/api#setchatmenubutton

### PR DESCRIPTION
**Pull request by faissaloux**
Resolves #194

```php
Telegraph::setChatMenuButton([
    "type" => "commands",
])->send();
```

> **Note**
> web_app type requires text and url.

```php
Telegraph::setChatMenuButton([
    "type" => "web_app",
    "text" => "VISIT",
    "url" => "https://www.telegram.org",
])->send();
```

### CODE REVIEW

**Comment by fabio-ivona** [comment]
@faissaloux this should implement the `menu_button` parameter as in https://core.telegram.org/bots/api#setchatmenubutton

**Comment by faissaloux** [comment]
@fabio-ivona ready!

> Resolves #194
> 
> ```
> Telegraph::setChatMenuButton([
>     "type" => "commands",
> ])->send();
> ```
> 
> > Note
> > web_app type requires text and url.
> 
> ```
> Telegraph::setChatMenuButton([
>     "type" => "web_app",
>     "text" => "VISIT",
>     "url" => "https://www.telegram.org",
> ])->send();
> ```

**Comment by fabio-ivona** [comment]
thanks, will take some days to review this

**Comment by fabio-ivona** [comment]
@faissaloux I refactored in order to use a ScopedPayload to obtain a more fluent interface

let me know if you like it :wink:

**Comment by faissaloux** [comment]
@fabio-ivona much better! well done 👌🏻

**Comment by fabio-ivona** [comment]
Will be released tomorrow

**Pull request merged**
