### PR TITLE
Fix UserDTO

### PR DESCRIPTION
**Pull request by ah-rahimi**
Hi,
 I want to use this DTO for [webapp user](https://core.telegram.org/bots/webapps#webappuser). 
 just Is_bot is Optional in the web app.

### CODE REVIEW

**Comment by ah-rahimi** [comment]
please merge it faster: @fabio-ivona 
Thanks a lot.

**Comment by fabio-ivona** [comment]
Hi @ah-rahimi sponsors have priority for pr and issues. We have planned this for merge in next release

**Comment by ah-rahimi** [comment]
Hi @fabio-ivona, you are right.
When is the estimated time of the next release?

**Comment by fabio-ivona** [comment]
Usually once a week

**Pull request merged**
