### PR TITLE
Implements sendSticker method

### PR DESCRIPTION
**Pull request by ivankuraev**
Implements sendSticker method
https://core.telegram.org/bots/api#sendsticker

### CODE REVIEW

**Comment by fabio-ivona** [comment]
Hi! Thanks for your contribution!

Would you mind to add tests and update the docs?

**Comment by ivankuraev** [comment]
Hi.

I didn't write tests before, but I can try.
I think, the send sticker test similar as document test.
It can accept "file_id" from sticker sets and also accept .tgs files.

About documentation, guess, no. My english is not native language, and I can't perfectly write.
Of cource, I can use Google translator for example, but this is not good solution for that.

**Comment by fabio-ivona** [comment]
Just try both, don't worry, I'll take care of fixing any issue, don't worry

**Comment by ivankuraev** [comment]
Hi.
I don't know how to fix that test.
In manual testing both variants, file_id and attach .tgs sticker, is work.

**Review by MarioGattolla — APPROVED** [review]
Fixed test and docs

**Pull request merged**
