### PR TITLE
chatMember method implemented

### LINKED ISSUE #259: Implement `getChatMember` method
https://core.telegram.org/bots/api#getchatmember

### PR DESCRIPTION
**Pull request by reza305z**
closes #259 

Telegram API getChatMember method is implemented as chatMember.

### CODE REVIEW

**Comment by fabio-ivona** [comment]
Thanks for your contribution! 🙌

**Comment by reza305z** [comment]
> Thanks for your contribution! 🙌

My Pleasure...

**Comment by elephantux** [comment]
I can't figure out how to use the command. If I just call it as described in the documentation, I get an exception No TelegraphChat defined for this request.

**Comment by fabio-ivona** [comment]
@elephantux would you mind to share your code?

**Comment by elephantux** [comment]
I found a solution. chatMember work's only with message command:
```
$channel = Chat::where('chat_id', '123456789')->first();
$response = $channel->message('member')->chatMember('987654321')->send();
```

**Pull request merged**
