### PR TITLE
implement sendMediaGroup [InputMediaPhoto]

### PR DESCRIPTION
**Pull request by YSRoot**
Use sample:
```
Telegraph::mediaGroup([
            (new InputMediaPhoto($url),
            (new InputMediaPhoto($fileId)),
            (new InputMediaPhoto(Storage::path('image.jpg'))),
        ])
            ->send();
```

### CODE REVIEW

**Comment by fabio-ivona** [comment]
hi @YSRoot, thanks for your contribution!

and +1 for the Validation class :ok_hand: 

would you mind adding tests and docs for your implementations?

**Comment by YSRoot** [comment]
ok, what kind of tests are needed? check that the dto methods work as expected with a link, a file id, and a file path? Also check that the correct data is generated (with a link, file ID and path to the file) when sending to telegrams? anything else?

**Comment by fabio-ivona** [comment]
@YSRoot the tests you mentioned are fine, thanks!

**Comment by YSRoot** [comment]
i update some logic in PR

refactor InputMedia logic
add support Stream for Attachment
add support preload file before send to Telegram

**Comment by fabio-ivona** [comment]
@YSRoot I'm putting this into draft, let me know when it's ready for a final review

**Comment by fabio-ivona** [comment]
I'm closing this because it seems inactive, please let me know if you are willing to keep working and I'll open it again

**Pull request closed without merging**
