### PR TITLE
Fix documentation WSOD

### PR DESCRIPTION
**Pull request by jorisdrenth**
As discussed in #453, this commit fixes a couple of things:

- White screen in documentation main page, 404 on all other pages
- Some documentation markdown files were deleted
- There was a FATAL error in Nuxt related to @nuxtjs/tailwindcss, that's why I pinned an slightly older version in package.json

Overall this fixes it, but I think the docs need a technical update since there still are a lot of errors / warnings when running the NPM commands to start Nuxt.

### CODE REVIEW

**Comment by jorisdrenth** [comment]
@fabio-ivona Do you have time to check this PR, so documentation will be available again? Thanks!

**Comment by fabio-ivona** [comment]
Just deploying in production, thanks @jorisdrenth

**Comment by fabio-ivona** [comment]
@jorisdrenth docs are back online, but image assets seems missing to me, could you please check it? I'm from phone right now and it is quite difficult for me

**Comment by jorisdrenth** [comment]
@fabio-ivona Sure, I'll take a look later today!

**Comment by fabio-ivona** [comment]
Update, just some images missing: eg. https://defstudio.github.io/quickstart/new-bot

**Comment by jorisdrenth** [comment]
@fabio-ivona See #455

**Comment by fabio-ivona** [comment]
Thanks @jorisdrenth you made my day! 🙌

**Pull request merged**
