### PR TITLE
Automatic dependencies resolution for callback action method

### PR DESCRIPTION
**Pull request by armivit**
Use Service Container [method invocation and injection](https://laravel.com/docs/10.x/container#method-invocation-and-injection).

Example:

```php
Keyboard::make()->buttons([
    Button::make('Generate')->action('generate')->param('id', '42'),
]);
```

WebhookHandler
```php
public function generate(UserRepository $repository, string $id): void
{
    $user = $repository->find($id); // $id = '42'
    // ...
}
```

### CODE REVIEW

**Comment by fabio-ivona** [comment]
Hi! Thanks for your contribution

Would to mind to add tests to your feature?

**Comment by armivit** [comment]
Added, but I'm not a big expert on tests

**Comment by fabio-ivona** [comment]
Thanks!
will review it in a few days

**Comment by fabio-ivona** [comment]
@armivit opened #475 to solve conflicts, I've put you as co-author

Thanks for your contribution, and sorry for the late merge :(

**Pull request closed without merging**
